routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Auth\LoginComponent;
use App\Http\Livewire\Dashboard\HomeComponent;
use App\Http\Livewire\Dashboard\Place\PlaceComponent;
use App\Http\Livewire\Dashboard\Route\RouteComponent;
use App\Http\Livewire\Dashboard\Client\ClientComponent;
use App\Http\Livewire\Dashboard\Place\NewPlaceComponent;
use App\Http\Livewire\Dashboard\Route\NewRouteComponent;
use App\Http\Livewire\Dashboard\Cashier\CashierComponent;
use App\Http\Livewire\Dashboard\Destiny\DestinyComponent;
use App\Http\Livewire\Dashboard\Package\PackageComponent;
use App\Http\Livewire\Dashboard\Place\EditPlaceComponent;
use App\Http\Livewire\Dashboard\Route\EditRouteComponent;
use App\Http\Livewire\Dashboard\Client\NewClientComponent;
use App\Http\Livewire\Dashboard\Client\EditClientComponent;
use App\Http\Livewire\Dashboard\Destiny\NewDestinyComponent;
use App\Http\Livewire\Dashboard\Package\NewPackageComponent;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', LoginComponent::class)->name('login');

// group dashboard routes
Route::group(['prefix' => 'dashboard'], function () {
    Route::get('/', HomeComponent::class)->middleware('auth')->name('dashboard');

    //Cashier routes
    Route::group(['prefix' => 'cashiers'], function () {
        Route::get('/', CashierComponent::class)->middleware('auth')->name('dashboard.cashiers');
    });

    //Clients routes
    Route::group(['prefix' => 'clients'], function () {
        Route::get('/', ClientComponent::class)->middleware('auth')->name('dashboard.clients');
        Route::get('/add', NewClientComponent::class)->middleware('auth')->name('dashboard.clients.add');
        Route::get('/edit/{id}', EditClientComponent::class)->middleware('auth')->name('dashboard.clients.edit');
    });

    //Places routes
    Route::group(['prefix' => 'places'], function () {
        Route::get('/', PlaceComponent::class)->middleware('auth')->name('dashboard.places');
        Route::get('/add', NewPlaceComponent::class)->middleware('auth')->name('dashboard.places.add');
        Route::get('/edit/{id}', EditPlaceComponent::class)->middleware('auth')->name('dashboard.places.edit');
    });

    //Destinies routes
    Route::group(['prefix' => 'destinies'], function () {
        Route::get('/', DestinyComponent::class)->middleware('auth')->name('dashboard.destinies');
        Route::get('/add', NewDestinyComponent::class)->middleware('auth')->name('dashboard.destinies.add');
    });

    //Routes routes
    Route::group(['prefix' => 'routes'], function () {
        Route::get('/', RouteComponent::class)->middleware('auth')->name('dashboard.routes');
        Route::get('/add', NewRouteComponent::class)->middleware('auth')->name('dashboard.routes.add');
        Route::get('/edit/{id}', EditRouteComponent::class)->middleware('auth')->name('dashboard.routes.edit');
    });

    //Packages routes
    Route::group(['prefix' => 'packages'], function () {
        Route::get('/', PackageComponent::class)->middleware('auth')->name('dashboard.packages');
        Route::get('/add', NewPackageComponent::class)->middleware('auth')->name('dashboard.packages.add');
    });

});

//logout
Route::get('/logout', function () {
    Auth::logout();
    return redirect()->route('login');
})->name('logout');

app/Models/Route.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Route extends Model
{
    use HasFactory;

    protected $fillable = [
        'place_id',
        'destiny_id',
        'price1',
        'price2',
        'price3',
        'status',
    ];

    public function place()
    {
        return $this->belongsTo(Place::class);
    }

    public function destiny()
    {
        return $this->belongsTo(Destiny::class);
    }

    public function scopeStatus($query)
    {
        return $query->where('status', true);
    }

    public function getDestinyNameAttribute()
    {
        return $this->destiny->name;
    }

    public function getPlaceNameAttribute()
    {
        return $this->place->name;
    }

    public function getPrice1Attribute($value)
    {
        return $value;
    }

    public function getPrice2Attribute($value)
    {
        return $value;
    }

    public function getPrice3Attribute($value)
    {
        return $value;
    }
}

app/Http/Livewire/Dashboard/Cashier/CashierComponent.php
<?php

namespace App\Http\Livewire\Dashboard\Cashier;

use App\Models\Cashier;
use Livewire\Component;
use PDF;
use App\Models\CashMovement;
use App\Models\PaymentMethod;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class CashierComponent extends Component
{
    public $cashier;
    public $movements;
    public $value;
    public $description;
    public $type;
    public $paymentMethod;
    public $paymentMethods;
    public $amount;
    public $state = [];

    public function mount()
    {
        $this->cashier = Cashier::where('user_id', auth()->user()->id)->where('place_id', session()->get('place_id'))->orderBy('id', 'desc')->first();

        if ($this->cashier) {
            $this->movements = CashMovement::where('user_id', auth()->user()->id)->where('cashier_id', $this->cashier->id)->get();
            $this->amount = $this->cashier->amount();
        }

        $this->paymentMethods = PaymentMethod::all();
    }

    public function openCashier()
    {
        Validator::make($this->state, [
            'value' => 'required|numeric',
            'description' => 'required',
            'type' => 'required',
            'paymentMethod' => 'required',
        ],[
            'value.required' => 'O valor é obrigatório',
            'value.numeric' => 'O valor deve ser numérico',
            'description.required' => 'A descrição é obrigatória',
            'type.required' => 'O tipo de movimentação é obrigatório',
            'paymentMethod.required' => 'O método de pagamento é obrigatório',
        ]);

        DB::transaction(function () {
            $cashier = Cashier::create([
                'user_id' => auth()->user()->id,
                'place_id' => session()->get('place_id'),
                'status' => 'open',
            ]);

            CashMovement::create([
                'cashier_id' => $cashier->id,
                'user_id' => auth()->user()->id,
                'payment_method_id' => $this->state['paymentMethod'],
                'type' => $this->state['type'],
                'value' => $this->state['value'],
                'description' => $this->state['description'],
            ]);
        });

        session()->flash('message', 'Caixa aberto com sucesso!');
        return redirect()->route('dashboard.cashiers');
    }

    public function closeCashier()
    {
        $this->cashier->update([
            'status' => 'close',
        ]);

        session()->flash('message', 'Caixa fechado com sucesso!');
        return redirect()->route('dashboard.cashiers');
    }

    public function exportData()
    {
        $cashier = $this->cashier;
        $movements = $this->movements;

        $pdfContent = PDF::loadView('livewire.dashboard.cashier.cashier-component', ['movements'=>$movements, 'cashier'=>$cashier])->output();
        return response()->streamDownload(
            fn () => print($pdfContent),
            "movimentacoes.pdf"
        );

    }

    public function render()
    {
        return view('livewire.dashboard.cashier.cashier-component');
    }
}

app/Http/Livewire/Dashboard/Cashier/NewCashierComponent.php
<?php

namespace App\Http\Livewire\Dashboard\Cashier;

use Livewire\Component;

class NewCashierComponent extends Component
{
    public function render()
    {
        return view('livewire.dashboard.cashier.new-cashier-component');
    }
}

app/Http/Livewire/Dashboard/Client/ClientComponent.php
<?php

namespace App\Http\Livewire\Dashboard\Client;

use PDF;
use App\Models\Client;
use Livewire\Component;


class ClientComponent extends Component
{
    public function mount()
    {
        $this->clients = Client::all();
    }

    public function exportData()
    {
        $clients = Client::orderBy('id', 'DESC')->get();

        $pdfContent = PDF::loadView('export.exportClients', ['clients' => $clients])->output();
        return response()->streamDownload(
            fn () => print($pdfContent),
            "clientes.pdf"
        );

        $this->dispatchBrowserEvent('alert', ['type' => 'success', 'message' => 'Dados exportados com sucesso!']);
    }

    public function delete($id = null)
    {
        try {
            $client = Client::find($id);
            $client->delete();

            $this->dispatchBrowserEvent('hideModal');
            $this->dispatchBrowserEvent('alert', [
                'type' => 'success',
                'title' => 'Sucesso!',
                'message' => 'Cliente excluído com sucesso!'
            ]);

            $this->mount();

        } catch (\Exception $e) {
            $this->dispatchBrowserEvent('alert', [
                'type' => 'error',
                'title' => 'Ops... Algo deu errado!',
                'message' => 'Erro ao excluir cliente!' . $e->getMessage()
            ]);
        }
    }


    public function render()
    {
        return view('livewire.dashboard.client.client-component');
    }
}

app/Http/Livewire/Dashboard/Client/EditClientComponent.php
<?php

namespace App\Http\Livewire\Dashboard\Client;

use App\Models\Client;
use Livewire\Component;

class EditClientComponent extends Component
{
    public $name;
    public $rg;
    public $cpfcnpj;
    public $email;
    public $phone;
    public $zip_code;
    public $address;
    public $number;
    public $complement;
    public $district;
    public $city;
    public $state;
    public $client_id;

    public function mount($id)
    {
        $client = Client::find($id);
        $this->name = $client->name;
        $this->rg = $client->rg;
        $this->cpfcnpj = $client->cpfcnpj;
        $this->email = $client->email;
        $this->phone = $client->phone;
        $this->zip_code = $client->zip_code;
        $this->address = $client->address;
        $this->number = $client->number;
        $this->complement = $client->complement;
        $this->district = $client->district;
        $this->city = $client->city;
        $this->state = $client->state;
        $this->client_id = $client->id;
    }

    public function render()
    {
        return view('livewire.dashboard.client.edit-client-component');
    }

    public function update()
    {
        $this->validate([
            'name' => 'required|min:3',
            'rg' => 'min:7',
            'cpfcnpj' => 'required|numeric|unique:clients,cpfcnpj,'.$this->client_id,
            'email' => 'required|email|unique:clients,email,'.$this->client_id,
            'phone' => 'required|min:10',
            'zip_code' => 'required|min:8',
            'address' => 'required',
            'number' => 'required',
            'district' => 'required',
            'city' => 'required',
            'state' => 'required',
        ],[
            'name.required' => 'O campo nome é obrigatório',
            'name.min' => 'O campo nome deve ter no mínimo 3 caracteres',
            'rg.min' => 'O campo RG deve ter no mínimo 7 caracteres',
            'cpfcnpj.required' => 'O campo CPF/CNPJ é obrigatório',
            'cpfcnpj.numeric' => 'O campo CPF/CNPJ deve conter apenas números',
            'cpfcnpj.unique' => 'O CPF/CNPJ informado já está cadastrado',
            'email.required' => 'O campo e-mail é obrigatório',
            'email.email' => 'O campo e-mail deve ser um e-mail válido',
            'email.unique' => 'O e-mail informado já está cadastrado',
            'phone.required' => 'O campo telefone é obrigatório',
            'phone.min' => 'O campo telefone deve ter no mínimo 10 caracteres',
            'zip_code.required' => 'O campo CEP é obrigatório',
            'zip_code.numeric' => 'O campo CEP deve conter apenas números',
            'zip_code.min' => 'O campo CEP deve ter no mínimo 8 caracteres',
            'address.required' => 'O campo endereço é obrigatório',
            'number.required' => 'O campo número é obrigatório',
            'district.required' => 'O campo bairro é obrigatório',
            'city.required' => 'O campo cidade é obrigatório',
            'state.required' => 'O campo estado é obrigatório',
        ]);

        try {
            $client = Client::find($this->client_id);
            $client->name = $this->name;
            $client->rg = $this->rg;
            $client->cpfcnpj = $this->cpfcnpj;
            $client->email = $this->email;
            $client->phone = $this->phone;
            $client->zip_code = $this->zip_code;
            $client->address = $this->address;
            $client->number = $this->number;
            $client->complement = $this->complement;
            $client->district = $this->district;
            $client->city = $this->city;
            $client->state = $this->state;
            $client->save();

            if ($client) {
                $this->reset();
                $this->dispatchBrowserEvent('alert', ['type' => 'success', 'message' => 'Cliente cadastrado com sucesso!']);

                return redirect()->route('dashboard.clients');
            }

        } catch (\Exception $e) {
            $this->dispatchBrowserEvent('alert', ['type' => 'error', 'message' => 'Erro ao cadastrar cliente! ' .$e->getMessage()]);
        }
    }

    public function viaCep()
    {
        $this->validate([
            'zip_code' => 'required|min:8|max:9',
        ],[
            'zip_code.required' => 'O campo CEP é obrigatório',
            'zip_code.min' => 'O campo CEP deve ter no mínimo 8 caracteres',
            'zip_code.max' => 'O campo CEP deve ter no máximo 9 caracteres',
        ]);

        $url = "https://viacep.com.br/ws/{$this->zip_code}/json/";

        $client = new \GuzzleHttp\Client();
        $response = $client->request('GET', $url);
        $data = json_decode($response->getBody());

        if (isset($data->erro)) {
            $this->dispatchBrowserEvent('alert', [
                'type' => 'error',
                'message' => 'Cep não encontrado! Tente novamente.',
                'title' => 'Ops... Algo deu errado!'
            ]);
            return;
        }

        $this->address = $data->logradouro;
        $this->district = $data->bairro;
        $this->city = $data->localidade;
        $this->state = $data->uf;
    }
}

app/Http/Livewire/Dashboard/Destiny/DestinyComponent.php
<?php

namespace App\Http\Livewire\Dashboard\Destiny;

use App\Models\Destiny;
use Livewire\Component;

class DestinyComponent extends Component
{
    public function mount()
    {
        $this->destinies = Destiny::all();
    }

    public function render()
    {
        return view('livewire.dashboard.destiny.destiny-component');
    }
}

app/Http/Livewire/Dashboard/Destiny/NewDestinyComponent.php
<?php

namespace App\Http\Livewire\Dashboard\Destiny;

use App\Models\Destiny;
use Livewire\Component;

class NewDestinyComponent extends Component
{
    public $name;
    public $phone;
    public $address;
    public $city;
    public $state;

    public function store()
    {
        $this->validate([
            'name' => 'required',
            'phone' => 'required',
            'address' => 'required',
            'city' => 'required',
            'state' => 'required',
        ],[
            'name.required' => 'O campo nome é obrigatório',
            'phone.required' => 'O campo telefone é obrigatório',
            'address.required' => 'O campo endereço é obrigatório',
            'city.required' => 'O campo cidade é obrigatório',
            'state.required' => 'O campo estado é obrigatório',
        ]);

        try {
            Destiny::create([
                'name' => $this->name,
                'phone' => $this->phone,
                'address' => $this->address,
                'city' => $this->city,
                'state' => $this->state,
            ]);

            $this->reset();
            $this->dispatchBrowserEvent('alert', ['type' => 'success',  'message' => 'Destino cadastrado com sucesso!']);
        } catch (\Exception $e) {
            $this->dispatchBrowserEvent('alert', ['type' => 'error',  'message' => 'Erro ao cadastrar destino!']);
        }
    }

    public function render()
    {
        return view('livewire.dashboard.destiny.new-destiny-component');
    }
}

app/Http/Livewire/Dashboard/Package/PackageComponent.php
<?php

namespace App\Http\Livewire\Dashboard\Package;

use App\Models\Package;
use Livewire\Component;

class PackageComponent extends Component
{
    public $packages;

    public function mount()
    {
        $this->packages = Package::all();
    }

    public function exportData()
    {
        return $this->packages;
    }

    public function render()
    {
        return view('livewire.dashboard.package.package-component');
    }
}

app/Http/Livewire/Dashboard/Place/PlaceComponent.php
<?php

namespace App\Http\Livewire\Dashboard\Place;

use App\Models\Place;
use Livewire\Component;

class PlaceComponent extends Component
{
    public $places;

    public function mount()
    {
        $this->places = Place::all();
    }

    public function render()
    {
        return view('livewire.dashboard.place.place-component');
    }
}

resources/views/livewire/dashboard/route/edit-route-component.blade.php
@section('title', 'Editar Rota')
<div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h3 class="card-title h3 mt-1 mb-0">
                            Editar Rota
                        </h3>
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <a href="{{ route('dashboard.routes') }}"
                                class="btn p-0  m-0 btn-sm btn-secondary float-right btn-icon-split">
                                <span class="icon text-white-50">
                                    <i class="fas fa-arrow-left text-warning"></i>
                                </span>
                                <span class="text">Voltar</span>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <form wire:submit.prevent="update">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Destino</label>
                                        <select wire:model.defer="destiny_id" class="form-control">
                                            <option value="">Selecione um destino</option>
                                            @foreach($destinies as $destiny)
                                            <option value="{{ $destiny->id }}">{{ $destiny->name }}</option>
                                            @endforeach
                                        </select>
                                        @error('destiny_id') <span class="text-danger">{{ $message }}</span> @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Valor 1</label>
                                        <input wire:model.defer="price1" type="text" class="form-control">
                                        @error('price1') <span class="text-danger">{{ $message }}</span> @enderror
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Valor 2</label>
                                        <input wire:model.defer="price2" type="text" class="form-control">
                                        @error('price2') <span class="text-danger">{{ $message }}</span> @enderror
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Valor 3</label>
                                        <input wire:model.defer="price3" type="text" class="form-control">
                                        @error('price3') <span class="text-danger">{{ $message }}</span> @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Status</label>
                                        <select wire:model.defer="status" class="form-control">
                                            <option value="">Selecione um status</option>
                                            <option value="1">Ativo</option>
                                            <option value="0">Inativo</option>
                                        </select>
                                        @error('status') <span class="text-danger">{{ $message }}</span> @enderror
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Salvar</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/dashboard/route/route-component.blade.php
@section('title', 'Rotas')
<div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-6 d-grid d-md-block">
                                <h4 class="title fw-bold mb-0">Listagem de Rotas</h4>
                            </div>
                            <div class="col-6 d-grid d-md-flex justify-content-md-end">
                                @if(Auth::user()->utype == 'admin')
                                <a href="{{ route('dashboard.routes.add') }}" class="btn btn-sm btn-outline-dark mb-0">
                                    <i class="fas fa-route text-warning"></i>&nbsp;
                                    Nova rota
                                </a>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="card-body" wire:ignore>
                        <div class="table-responsive">
                            <table class="table table-striped table-hover" id="tableDestiny">
                                <thead>
                                    <tr>
                                        <th>Origem</th>
                                        <th>Destino</th>
                                        <th>Valor 1</th>
                                        <th>Valor 2</th>
                                        <th>Valor 3</th>
                                        <th class="text-center">Status</th>
                                        <th class="text-center">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($routes as $route)
                                    <tr>
                                        <td>{{ $route->place_name }}</td>
                                        <td>{{ $route->destiny_name }}</td>
                                        <td>R$ {{ str_replace('.', ',', $route->price1) }}</td>
                                        <td>R$ {{ str_replace('.', ',', $route->price2) }}</td>
                                        <td>R$ {{ str_replace('.', ',', $route->price3) }}</td>
                                        <td class="text-center">
                                            @if($route->status == '1')
                                            <span class="badge bg-success">Ativo</span>
                                            @else
                                            <span class="badge bg-danger">Inativo</span>
                                            @endif
                                        </td>
                                        <td class="text-center">
                                            <!-- <a href="" class="btn btn-sm btn-outline-dark m-0" title="Vizualizar">
                                                <i class="fas fa-eye"></i>
                                            </a> -->
                                            <a href="{{ route('dashboard.routes.edit', [$route->id])}}" class="btn btn-sm btn-outline-warning m-0" title="Editar">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <button type="button" class="btn btn-outline-danger btn-sm m-0" title="Deletar" wire:click="delete({{ $route->id }})">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <x-export-button />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section('scripts')
    <script>
        $(document).ready(function() {
            $('#tableDestiny').DataTable({
                drawCallback: function () {
                    $('.page-link').addClass('btn-sm text-dark');
                    $('.page-item.active .page-link').addClass('bg-dark text-white border-dark');
                    $('.dataTables_empty').addClass('lead');
                },
                responsive: true,
                columnDefs: [
                    { orderable: false, targets: [6] }
                ],
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "zeroRecords": "Nenhum registro encontrado",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "Nenhum registro disponível",
                    "infoFiltered": "(filtrado de _MAX_ registros no total)",
                    "search": "Pesquisar",
                    "paginate": {
                        "previous": "Anterior",
                        "next": "Próximo"
                    }
                }
            });
        });
    </script>
@endsection